### ISSUE TITLE
Dictionary exception when running java.util.zip testcases with Nxgzip

### ISSUE THREAD

**Issue by charleschen2000** [libnxz/power-gzip#204]
OS: RHEL 8.6
kernel: 4.18.0-372.9.1.el8.ppc64le
jdk version: IBM Semeru Runtime Certified Edition 17.0.7.0 (build 17.0.7+7)
when running java.util.zip testcase DeInflate with Nxgzip, got the following dictionary exception:
```
#javac DeInflate.java
# LD_PRELOAD=/home/nxgzip/power-gzip-0.64/lib/.libs/libnxz.so.0.0.64 java DeInflate
level:-1, strategy: 0, dowrap: false
level:-1, strategy: 0, dowrap: true
Exception in thread "main" java.lang.RuntimeException: checkDict failed: need dict to continue
        at DeInflate.checkDict(DeInflate.java:223)
        at DeInflate.main(DeInflate.java:300)
```

The DeInflate test case can run without problem if not using NXgzip:
```
# java DeInflate
level:-1, strategy: 0, dowrap: false
level:-1, strategy: 0, dowrap: true
level:-1, strategy: 1, dowrap: false
level:-1, strategy: 1, dowrap: true
level:-1, strategy: 2, dowrap: false
level:-1, strategy: 2, dowrap: true
level:0, strategy: 0, dowrap: false
level:0, strategy: 0, dowrap: true
level:0, strategy: 1, dowrap: false
level:0, strategy: 1, dowrap: true
level:0, strategy: 2, dowrap: false
level:0, strategy: 2, dowrap: true
level:1, strategy: 0, dowrap: false
level:1, strategy: 0, dowrap: true
level:1, strategy: 1, dowrap: false
level:1, strategy: 1, dowrap: true
level:1, strategy: 2, dowrap: false
level:1, strategy: 2, dowrap: true
level:2, strategy: 0, dowrap: false
level:2, strategy: 0, dowrap: true
level:2, strategy: 1, dowrap: false
level:2, strategy: 1, dowrap: true
level:2, strategy: 2, dowrap: false
level:2, strategy: 2, dowrap: true
level:3, strategy: 0, dowrap: false
level:3, strategy: 0, dowrap: true
level:3, strategy: 1, dowrap: false
level:3, strategy: 1, dowrap: true
level:3, strategy: 2, dowrap: false
level:3, strategy: 2, dowrap: true
level:4, strategy: 0, dowrap: false
level:4, strategy: 0, dowrap: true
level:4, strategy: 1, dowrap: false
level:4, strategy: 1, dowrap: true
level:4, strategy: 2, dowrap: false
level:4, strategy: 2, dowrap: true
level:5, strategy: 0, dowrap: false
level:5, strategy: 0, dowrap: true
level:5, strategy: 1, dowrap: false
level:5, strategy: 1, dowrap: true
level:5, strategy: 2, dowrap: false
level:5, strategy: 2, dowrap: true
level:6, strategy: 0, dowrap: false
level:6, strategy: 0, dowrap: true
level:6, strategy: 1, dowrap: false
level:6, strategy: 1, dowrap: true
level:6, strategy: 2, dowrap: false
level:6, strategy: 2, dowrap: true
level:7, strategy: 0, dowrap: false
level:7, strategy: 0, dowrap: true
level:7, strategy: 1, dowrap: false
level:7, strategy: 1, dowrap: true
level:7, strategy: 2, dowrap: false
level:7, strategy: 2, dowrap: true
level:8, strategy: 0, dowrap: false
level:8, strategy: 0, dowrap: true
level:8, strategy: 1, dowrap: false
level:8, strategy: 1, dowrap: true
level:8, strategy: 2, dowrap: false
level:8, strategy: 2, dowrap: true
level:9, strategy: 0, dowrap: false
level:9, strategy: 0, dowrap: true
level:9, strategy: 1, dowrap: false
level:9, strategy: 1, dowrap: true
level:9, strategy: 2, dowrap: false
level:9, strategy: 2, dowrap: true
```

this issue seems to be related with #202 . 
java test code:
[https://github.com/openjdk/jdk11u/blob/jdk-11.0.19%2B7/test/jdk/java/util/zip/DeInflate.java]
Could you please help to take a look, thanks.

**Comment by sachinmonga64** [comment]
Hi

As discussed , this issue will NOT be fixed because of restriction of libnxz. Please find below the detailed reasoning.

This is the test case named "DeInflate.java" from java test-suite.

1. The objective of this test is to check all the combinations of Compression Levels, Compression Strategies and Wrapping.
2. The test also checks and changes levels and Strategies dynamically using APIs like setStrategy( ) and setLevel( ) etc. 
3. The test also sets dictionary etc. dynamically.

The present reported error **_Exception in thread "main" java.lang.RuntimeException: checkDict failed: need dict to continue_** is fixed.  However, after the fix , the case is facing another  error which is as below:
`Exception in thread "main" java.lang.InternalError: unknown error in checkDeflateStatus`

Please find below the reason for the same.

The compression strategies which are getting checked in the test case are :

- Z_DEFAULT_STRATEGY
- Z_FILTERED
- Z_HUFFMAN_ONLY
- Z_RLE
- Z_FIXED

1. Libnxz 0.63 does not support `Z_FILTERED , Z_HUFFMAN_ONLY and Z_RLE` for zlib format. Setting these strategies for NX would result in Internal Error. 
2. Libnxz does not support **dynamic level** and `dynamic strategy` setting also .  It means that libnxz only acknowledges level and strategy before compression starts. Once compression is initiated , it cannot change these settings for remaining part of the compression. However we have tried to facilitate this change dynamically by providing deflateParams( ) definition of NX after certain checking.

After applying the fix for the error _**"need dict to continue"**_, and changing the strategies inside the java test-case for libnxz supported ones, the test case is getting Passed. So, I will provide the fix for the 1st error after detailed testing.

**Comment by aolitianya** [comment]
we find when the length of dataIn between 1024 and 8192， another error will occur， Details are as follows：
      level:-1, strategy: 0, dowrap: false
      len=524288
      len=245591
      len=361647
      len=383894
      len=29918
      level:-1, strategy: 0, dowrap: true
      len=524288
      len=119491
      len=140488
      len=8724
      len=1986
      m=1991, n=0, len=1986, eq=false
      Exception in thread "main" java.lang.RuntimeException: De/inflater failed:java.util.zip.Deflater@3b9a45b3
              at DeInflate.check(DeInflate.java:141)
              at DeInflate.main(DeInflate.java:294)

**Comment by charleschen2000** [comment]
From our point of view, we could understand that NX unit can only support limited strategies (Z_DEFAULT_STRATEGY/Z_FIXED).
However, we think libnxz should be able to support Z_NO_COMPRESSION (level=0), since it does NOT need any processing in NX unit, just need to copy input to output uncompressed. 
Thus we would like to know if there is any hinder supporting level 0 compression? Thanks.

**Comment by chenhealth1234** [comment]
Dear ,

Appreciate a lot for your great support. With the patch the testing is passed. We will do further testing as customer's request, if any question, we will give you update ASAP. Thanks again.

**Comment by sachinmonga64** [comment]
Hi

Sorry for the late reply as I was on leave.
Please find below my replies and further queries.

>_So we did some further research, and found that after applying patch 0005 & 0006, the deflate behavior changed to sw only._   

Firstly, Do you think only this case has performance issues or you have more cases ?
Majority of the test cases from java test-suite test zip file format. `Libnxz` does not support zip file format. It only supports zlib and gzip formats. So, We tried to route all unsupported file format cases to s/w route for this reason.
If this is the only case for performance concern , then I need to check what kind of file format is getting tested etc.
We are looking into it and will reply for any development.

Secondly, please let me know how are you checking the performance parameters ?
Are you using another utility for compression/decompression ? Or you have any existing benchmark available with you ?

**Comment by charleschen2000** [comment]
Dear,
we used other tests for comparison too, for example, the "pigz" command as shown below. We found that when libnxz is referenced, the deflateInit  always got zero strm->avail_in & zero strm->total_in from input stream parameter:
```
[root@p10nxgzip power-gzip]# time LD_PRELOAD=/root/power-gzip/lib/.libs/libnxz.so  unpigz test.txt.gz

real    0m7.570s
user    0m7.938s
sys     0m0.953s
[root@p10nxgzip power-gzip]# time LD_PRELOAD=/root/power-gzip/lib/.libs/libnxz.so  pigz test.txt

real    0m5.214s
user    0m56.062s
sys     0m2.123s
[root@p10nxgzip power-gzip]# time unpigz test.txt.gz

real    0m7.573s
user    0m8.018s
sys     0m0.943s
[root@p10nxgzip power-gzip]# time pigz test.txt

real    0m4.761s
user    0m57.302s
sys     0m0.832s
```

Again we got the following from /tmp/nx.log (**deflate(nx): 0**):
`[2023/09/26 08:31:54] pid 1945333: Info: call sw_deflateEnd,rc=-3
[2023/09/26 08:31:54] pid 1945333: ### API call statistic:
[2023/09/26 08:31:54] pid 1945333: ### deflateInit: 16
[2023/09/26 08:31:54] pid 1945333: ### deflate: 65534
[2023/09/26 08:31:54] pid 1945333: ###  deflate(sw): 65534
[2023/09/26 08:31:54] pid 1945333: ###  deflate(nx): 0
[2023/09/26 08:31:54] pid 1945333: ###   deflate_avail_in    4 KiB: 32766
[2023/09/26 08:31:54] pid 1945333: ###   deflate_avail_in  132 KiB: 32768
[2023/09/26 08:31:54] pid 1945333: ###   deflate_avail_out  168 KiB: 32766
[2023/09/26 08:31:54] pid 1945333: ###   deflate_avail_out  172 KiB: 32768
[2023/09/26 08:31:54] pid 1945333: ### deflateBound: 0
[2023/09/26 08:31:54] pid 1945333: ### deflateEnd: 16`

It shows that input_len is always 0 when debugging into "deflateInit2_":
`int input_len = strm->avail_in + strm->total_in;
        prt_info("input_len = %d\n", input_len);
        if(input_len > COMPRESS_THRESHOLD &&
          (nx_config.mode.deflate == GZIP_AUTO || nx_config.mode.deflate == GZIP_MIX)){
`

We can switch back to NX approach after comment the input_len checking above, and comment the "deflate" call in nx_deflateParams below:

```
 /* Empty the contents of buffer */
       /*int err = deflate(strm, Z_BLOCK);
       if (err == Z_STREAM_ERROR)
               return err;

       if (strm->avail_in)
               return Z_BUF_ERROR;*/
```
the log shows NX approach is used:
`[2023/09/26 10:25:41] pid 1957622: Info: nx_free_buffer: free 0x200034050000 len 6144
[2023/09/26 10:25:41] pid 1957622: ### API call statistic:
[2023/09/26 10:25:41] pid 1957622: ### deflateInit: 16
[2023/09/26 10:25:41] pid 1957622: ### deflate: 32768
[2023/09/26 10:25:41] pid 1957622: ###  deflate(sw): 0
[2023/09/26 10:25:41] pid 1957622: ###  deflate(nx): 32768
[2023/09/26 10:25:41] pid 1957622: ###   deflate_avail_in  132 KiB: 32768
[2023/09/26 10:25:41] pid 1957622: ###   deflate_avail_out  172 KiB: 32768
`

**Comment by charleschen2000** [comment]
Dear,
we used other tests for comparison too, for example, the "pigz" command as shown below. We found that when libnxz is referenced, the deflateInit  always got zero strm->avail_in & zero strm->total_in from input stream parameter:
```
[root@p10nxgzip power-gzip]# time LD_PRELOAD=/root/power-gzip/lib/.libs/libnxz.so  unpigz test.txt.gz

real    0m7.570s
user    0m7.938s
sys     0m0.953s
[root@p10nxgzip power-gzip]# time LD_PRELOAD=/root/power-gzip/lib/.libs/libnxz.so  pigz test.txt

real    0m5.214s
user    0m56.062s
sys     0m2.123s
[root@p10nxgzip power-gzip]# time unpigz test.txt.gz

real    0m7.573s
user    0m8.018s
sys     0m0.943s
[root@p10nxgzip power-gzip]# time pigz test.txt

real    0m4.761s
user    0m57.302s
sys     0m0.832s
```

Again we got the following from /tmp/nx.log (**deflate(nx): 0**):
`[2023/09/26 08:31:54] pid 1945333: Info: call sw_deflateEnd,rc=-3
[2023/09/26 08:31:54] pid 1945333: ### API call statistic:
[2023/09/26 08:31:54] pid 1945333: ### deflateInit: 16
[2023/09/26 08:31:54] pid 1945333: ### deflate: 65534
[2023/09/26 08:31:54] pid 1945333: ###  deflate(sw): 65534
[2023/09/26 08:31:54] pid 1945333: ###  deflate(nx): 0
[2023/09/26 08:31:54] pid 1945333: ###   deflate_avail_in    4 KiB: 32766
[2023/09/26 08:31:54] pid 1945333: ###   deflate_avail_in  132 KiB: 32768
[2023/09/26 08:31:54] pid 1945333: ###   deflate_avail_out  168 KiB: 32766
[2023/09/26 08:31:54] pid 1945333: ###   deflate_avail_out  172 KiB: 32768
[2023/09/26 08:31:54] pid 1945333: ### deflateBound: 0
[2023/09/26 08:31:54] pid 1945333: ### deflateEnd: 16`

It shows that input_len is always 0 when debugging into "deflateInit2_":
`int input_len = strm->avail_in + strm->total_in;
        prt_info("input_len = %d\n", input_len);
        if(input_len > COMPRESS_THRESHOLD &&
          (nx_config.mode.deflate == GZIP_AUTO || nx_config.mode.deflate == GZIP_MIX)){
`

We can switch back to NX approach after comment the input_len checking above, and comment the "deflate" call in nx_deflateParams below:

```
 /* Empty the contents of buffer */
       /*int err = deflate(strm, Z_BLOCK);
       if (err == Z_STREAM_ERROR)
               return err;

       if (strm->avail_in)
               return Z_BUF_ERROR;*/
```
the log now shows NX approach is used:
`[2023/09/26 10:25:41] pid 1957622: Info: nx_free_buffer: free 0x200034050000 len 6144
[2023/09/26 10:25:41] pid 1957622: ### API call statistic:
[2023/09/26 10:25:41] pid 1957622: ### deflateInit: 16
[2023/09/26 10:25:41] pid 1957622: ### deflate: 32768
[2023/09/26 10:25:41] pid 1957622: ###  deflate(sw): 0
[2023/09/26 10:25:41] pid 1957622: ###  deflate(nx): 32768
[2023/09/26 10:25:41] pid 1957622: ###   deflate_avail_in  132 KiB: 32768
[2023/09/26 10:25:41] pid 1957622: ###   deflate_avail_out  172 KiB: 32768
`

**Comment by sachinmonga64** [comment]
Dear,

Thanks for sharing the information.

But are you not facing the below error after undoing `input_len` change and commenting deflate call in `nx_deflateParams( )`  ?

 ```
LD_PRELOAD=/home/sachin/java_libnxz/0.63_final/power-gzip/lib/.libs/libnxz.so java DeInflate
level:-1, strategy: 0, dowrap: false
level:-1, strategy: 0, dowrap: true
level:-1, strategy: 1, dowrap: false
level:-1, strategy: 1, dowrap: true
level:-1, strategy: 2, dowrap: false
level:-1, strategy: 2, dowrap: true
level:0, strategy: 0, dowrap: false
Exception in thread "main" java.lang.InternalError: unknown error in checkDeflateStatus
	at java.base/java.util.zip.Deflater.deflateBytesBytes(Native Method)
	at java.base/java.util.zip.Deflater.deflate(Deflater.java:595)
	at java.base/java.util.zip.Deflater.deflate(Deflater.java:474)
	at java.base/java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:251)
	at java.base/java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:211)
	at DeInflate.checkStream(DeInflate.java:52)
	at DeInflate.main(DeInflate.java:296)
```
Also,  the feasibility of commenting the deflate( ) under `nx_deflateParams` needs to be checked.

**Comment by charleschen2000** [comment]
Dear, 
Yes we are facing the same error  after undoing input_len change and commenting deflate call in nx_deflateParams( ). However, we are able to see that NX unit is used  from /tmp/nx.log after those changes made.

```
[root@p10nxgzip zip]#  LD_PRELOAD=/root/power-gzip/lib/.libs/libnxz.so  java DeInflate
level:-1, strategy: 0, dowrap: false
level:-1, strategy: 0, dowrap: true
level:-1, strategy: 1, dowrap: false
level:-1, strategy: 1, dowrap: true
level:-1, strategy: 2, dowrap: false
level:-1, strategy: 2, dowrap: true
level:0, strategy: 0, dowrap: false
Exception in thread "main" java.lang.InternalError: unknown error in checkDeflateStatus
        at java.base/java.util.zip.Deflater.deflateBytesBytes(Native Method)
        at java.base/java.util.zip.Deflater.deflate(Deflater.java:586)
        at java.base/java.util.zip.Deflater.deflate(Deflater.java:465)
        at java.base/java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:250)
        at java.base/java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:210)
        at DeInflate.checkStream(DeInflate.java:52)
        at DeInflate.main(DeInflate.java:296)
        Suppressed: java.lang.InternalError: unknown error in checkDeflateStatus
                at java.base/java.util.zip.Deflater.deflateBytesBytes(Native Method)
                at java.base/java.util.zip.Deflater.deflate(Deflater.java:586)
                at java.base/java.util.zip.Deflater.deflate(Deflater.java:465)
                at java.base/java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:250)
                at java.base/java.util.zip.DeflaterOutputStream.finish(DeflaterOutputStream.java:225)
                at java.base/java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:237)
                at DeInflate.checkStream(DeInflate.java:51)
                ... 1 more
[root@p10nxgzip zip]# grep "(nx)" /tmp/nx.log
[2023/09/26 16:31:59] pid 1967063: ###  deflate(nx): 32768
[2023/09/26 16:31:59] pid 1967063: ###  inflate(nx): 0
[2023/09/26 16:32:09] pid 1967083: ###  deflate(nx): 0
[2023/09/26 16:32:09] pid 1967083: ###  inflate(nx): 0
[2023/09/26 16:32:21] pid 1967092: ###  deflate(nx): 17892
[2023/09/26 16:32:21] pid 1967092: ###  inflate(nx): 358

```

The pigz command worked fine and showed performance improvement over sw approach:
```
[root@p10nxgzip power-gzip]# time pigz test.txt

real    0m4.385s
user    0m57.862s
sys     0m0.721s
[root@p10nxgzip power-gzip]# time unpigz test.txt

real    0m7.655s
user    0m8.145s
sys     0m0.898s
[root@p10nxgzip power-gzip]# time LD_PRELOAD=/root/power-gzip/lib/.libs/libnxz.so pigz test.txt

real    0m3.189s
user    0m5.119s
sys     0m5.071s
[root@p10nxgzip power-gzip]# time LD_PRELOAD=/root/power-gzip/lib/.libs/libnxz.so unpigz test.txt.gz

real    0m7.690s
user    0m8.119s
sys     0m1.115s

[2023/09/26 16:35:37] pid 1967200: ###  deflate(nx): 32768
[2023/09/26 16:35:37] pid 1967200: ###  inflate(nx): 0
[2023/09/26 16:35:58] pid 1967221: ###  deflate(nx): 0
[2023/09/26 16:35:58] pid 1967221: ###  inflate(nx): 0

```

**Comment by sachinmonga64** [comment]
Can you please share the patch at your end ?  I am not able to re-create the scenario.

In my case , even after `unknown error in checkDeflateStatus` , the nx log shows s/w route.

```
less nx.log
...
[2023/09/26 04:17:03] pid 3415452: ### deflateInit: 8
[2023/09/26 04:17:03] pid 3415452: ### deflate: 46
[2023/09/26 04:17:03] pid 3415452: ###  deflate(sw): 46
[2023/09/26 04:17:03] pid 3415452: ###  deflate(nx): 0
..
```

**Comment by charleschen2000** [comment]
[0001-undo-input_len-check-and-comment-deflate-call-in-def.patch](https://github.com/libnxz/power-gzip/files/12727673/0001-undo-input_len-check-and-comment-deflate-call-in-def.patch)

**Comment by charleschen2000** [comment]
> [0001-undo-input_len-check-and-comment-deflate-call-in-def.patch](https://github.com/libnxz/power-gzip/files/12727673/0001-undo-input_len-check-and-comment-deflate-call-in-def.patch)
Dear,
The test steps fyi... Please let me know if there's any problem, thanks.
```

[root@p10nxgzip ~]# export NX_GZIP_TRACE=8
[root@p10nxgzip ~]# cd zip
[root@p10nxgzip zip]# > /tmp/nx.log
[root@p10nxgzip zip]#  LD_PRELOAD=/root/power-gzip/lib/.libs/libnxz.so  java DeInflate
level:-1, strategy: 0, dowrap: false
level:-1, strategy: 0, dowrap: true
level:-1, strategy: 1, dowrap: false
level:-1, strategy: 1, dowrap: true
level:-1, strategy: 2, dowrap: false
level:-1, strategy: 2, dowrap: true
level:0, strategy: 0, dowrap: false
Exception in thread "main" java.lang.InternalError: unknown error in checkDeflateStatus
        at java.base/java.util.zip.Deflater.deflateBytesBytes(Native Method)
        at java.base/java.util.zip.Deflater.deflate(Deflater.java:586)
        at java.base/java.util.zip.Deflater.deflate(Deflater.java:465)
        at java.base/java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:250)
        at java.base/java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:210)
        at DeInflate.checkStream(DeInflate.java:52)
        at DeInflate.main(DeInflate.java:296)
        Suppressed: java.lang.InternalError: unknown error in checkDeflateStatus
                at java.base/java.util.zip.Deflater.deflateBytesBytes(Native Method)
                at java.base/java.util.zip.Deflater.deflate(Deflater.java:586)
                at java.base/java.util.zip.Deflater.deflate(Deflater.java:465)
                at java.base/java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:250)
                at java.base/java.util.zip.DeflaterOutputStream.finish(DeflaterOutputStream.java:225)
                at java.base/java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:237)
                at DeInflate.checkStream(DeInflate.java:51)
                ... 1 more
[root@p10nxgzip zip]# less /tmp/nx.log
...
[2023/09/26 20:55:14] pid 1972729: nx_deflate.c:1654: Error: can not make progress on s3, loop_cnt = 65535
[2023/09/26 20:55:14] pid 1972729: nx_deflate.c:1654: Error: can not make progress on s3, loop_cnt = 65535
[2023/09/26 20:55:14] pid 1972729: ### API call statistic:
[2023/09/26 20:55:14] pid 1972729: ### deflateInit: 36
[2023/09/26 20:55:14] pid 1972729: ### deflate: 18811
[2023/09/26 20:55:14] pid 1972729: ###  deflate(sw): 6
[2023/09/26 20:55:14] pid 1972729: ###  deflate(nx): 18805

```

**Comment by sachinmonga64** [comment]
Hi

I have investigated the above error `java.lang.InternalError: unknown error in checkDeflateStatus`

This error is occurring when level is set as 0 (Z_NO_COMPRESSION). As I stated earlier also, libnxz does not have handling of Z_NO_COMPRESSION. 

I tried to handle this level within libnxz by simply copying input buffer(next_in) to the output_buffer(next_out) and advancing the required pointers(avail_in, avail_out, used_out, used_in etc). It seemed that the code worked fine as I was able to proceed the above error.

However, we faced further error while inflating back. When I checked the zlib deflate code for level=Z_NO_COMPRESSION , I found that  alot of changes are required and simple copying will not work.
I guess there must be some specific reason why it was not handled within libnxz during its development. Perhaps , it was to ensure to use NX resource for some meaningful level.

Now, since we are able to achieve NX route by undoing `input_len` patch, we can set s/w fallback for this particular level(Z_NO_COMPRESSION) as a solution.

Let me know you views.

**Comment by charleschen2000** [comment]
Thanks. I think it would be fine if we could do the sw fallback in libnxz.
---- Replied Message ----
| From | ***@***.***> |
| Date | 09/29/2023 14:39 |
| To | libnxz/power-gzip ***@***.***> |
| Cc | charleschen2000 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [libnxz/power-gzip] Dictionary exception when running java.util.zip testcases with Nxgzip (Issue #204) |

Hi

I have investigated the above error java.lang.InternalError: unknown error in checkDeflateStatus

This error is occurring when level is set as 0 (Z_NO_COMPRESSION). As I stated earlier also, libnxz does not have handling of Z_NO_COMPRESSION.

I tried to handle this level within libnxz by simply copying input buffer(next_in) to the output_buffer(next_out) and advancing the required pointers(avail_in, avail_out, used_out, used_in etc). It seemed that the code worked fine as I was able to proceed the above error.

However, we faced further error while inflating back. When I checked the zlib deflate code for level=Z_NO_COMPRESSION , I found that alot of changes are required and simple copying will not work.
I guess there must be some specific reason why it was not handled within libnxz during its development. Perhaps , it was to ensure to use NX resource for some meaningful level.

Now, since we are able to achieve NX route by undoing input_len patch, we can set s/w fallback for this particular level(Z_NO_COMPRESSION) as a solution.

Let me know you views.

**Comment by sachinmonga64** [comment]
Hi

PFA the new patch. [0001-Fix-Deflate-without-fallback.patch](https://github.com/libnxz/power-gzip/files/13070090/0001-Fix-Deflate-without-fallback.patch)

Request you to please apply 1st 4 patches and then the shared patch (0001-Fix-Deflate-without-fallback.patch).

This should resolve all errors(unknown error in checkDeflateStatus + runtime error)

Regards:

**Comment by sachinmonga64** [comment]
Hi

Request you to please close the tickets #203, #204 and #205 if the issues are resolved with the latest shared patches.

Regards:
Sachin.
